### ISSUE TITLE
import.sh crashes after importing data in mongo

### ISSUE THREAD

**Issue by jschne** [alchemy-fr/GeonamesServer#16]
Hi,

I have this message while running import.sh :

> PHP Warning:  require_once(/home/sites_web/GeonamesServer/import/vendor/autoload.php): failed to open stream: Aucun fichier ou dossier de ce type in /home/sites_web/GeonamesServer/import/index.php on line 5
> PHP Fatal error:  require_once(): Failed opening required '/home/sites_web/GeonamesServer/import/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/sites_web/GeonamesServer/import/index.php on line 5

Is there something missing on the documentation or a real problem in the script ?

Regards

**Comment by jschne** [comment]
ok I've seen where is the problem

I had to run composer in import dir, You must add this step in the documentation

**Comment by romainneutron** [comment]
No, this is an issue, composer has to run at the root of the project
