### ISSUE TITLE
Add support for ascii folding

### ISSUE THREAD

**Issue by nlegoff** [alchemy-fr/GeonamesServer#34]
Given "paris-l'hôpital" is indexed
Looking for paris-l'hopital returns 0 result

**Comment by romainneutron** [comment]
Is the same bug happens for orléans, or any city containing a diacritic ?

**Comment by csaoh** [comment]
orléans worked on v1

**Comment by romainneutron** [comment]
actually your examplr is not very good @nlegoff , it contains `'`, `-`, and `ô`

**Comment by csaoh** [comment]
I'd even add that cyrillic characters worked in v1 too, so still must be the case.

**Comment by nlegoff** [comment]
@romainneutron Yes it is the same for any indexed terms with diacritics
@csaoh The issue is not about not finding "orléans" when looking for "orléans" but to be able to find "orléans" when looking for "orleans" without the accent or any diacritics characters in the query

I think we should support this use case.

**Comment by romainneutron** [comment]
I think you did not understand @csaoh ; He said that in v1, when querying `Orléans`, `orleans`, or `orléans`, you were able to find `Orléans`

This is just an ES setting
