### ISSUE TITLE
Request: Admin Code Lookup

### ISSUE THREAD

**Issue by adamlc** [alchemy-fr/GeonamesServer#64]
It would be nice if we could also return the Administration Area for city results too. These can be looked up by joining the various admin codes together and querying the data in admin2Codes and admin1CodesASCII. 

It appears that admin1Codes is already in the database, but admin2Codes isn't. Its only a small amount of data so shouldn't really impact performance in any way.

I would have a go myself but unfortunately I know nothing about nodejs, I'm a PHP developer.

Adam

**Comment by romainneutron** [comment]
:+1: Any idea @nlegoff ?
