### ISSUE TITLE
JSONP Callback Lowercase

### ISSUE THREAD

**Issue by adamlc** [alchemy-fr/GeonamesServer#65]
Im not sure if something is wrong with my configuration but when I make a call to my server using JSONP the callback always get set as lower case.

Eg. http://ins-sentry-geoname-eu1a-1.jumplead.com:3000/city?name=paris&limit=8&callback=myFunction

(notice the uppercase F on myFunction);

Gets returned as this:

myfunction(**content**)

Which means that it breaks jQuery's native jsonp ajax implementation unless you pass a lower case callback function.

**Comment by nlegoff** [comment]
Thanks for reporting, this issue has been adressed in https://github.com/alchemy-fr/GeonamesServer/pull/66
